### ISSUE TITLE
/rc channels held constant if /send_rc is non zero

### ISSUE THREAD

**Issue by damanfb** [cberzan/roscopter#12]
I'm trying to set up a node that reads in the topic /rc to get the values of the joysticks from my RC transmitter. I then want to augment those values and pass them along to /send_rc. However, whenever I have values being sent to /send_rc, the /rc topic holds the roll, pitch, and yaw channels constant at 1500 and does not respond to my RC transmitter. Is this a function within mavlink or something I can change in roscopter?

**Comment by ssk2** [comment]
From memory (which is getting increasingly rusty), this is a setting on your transmitter / autopilot and not Roscopter. The default value of 1500 suggests that it's not passing through the actual values - usually 1500 is the default.

**Comment by damanfb** [comment]
Does this seem like something I need to set in the mission planner configs then? The way I have it is I read one of the switches on the /rc topic and if it is a certain value I set /send_rc to zero, passing through my transmitter. When I do this, I can see from the echo of /rc that the values are changing with my transmitter. As soon as I try to set /send_rc to some nonzero vlaue in roll, pitch, thrust, yaw then when I echo the /rc topic it sets roll, pitch, and yaw to zero. I'm not sure how this would be something on the transmitter though.
